import { NextResponse } from 'next/server'
const BASE = [
  { id: "paracetamol-bp", name: "Paracetamol Powder BP/USP 99% 25kg Drum", category: "Industrial chemicals", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "PARACETAMOL BP/USP", company: "Hebei Pharmaceutical – Verified", moq: "100kg", price: "Request DDP Quote – Valid 3 Days – Only DDP", image: "https://via.placeholder.com/400x300/1e40af/ffffff?text=Paracetamol", sourceCompany: "Hebei Pharmaceutical", sourcePlatform: "1688", sourceUrl: "https://m.1688.com/product/paracetamol", description: "Paracetamol Powder", grade: "Pharma Grade", tab: "Industrial chemicals" },
  { id: "sorbitol-usp", name: "Sorbitol Crystallized USP 25kg Bag", category: "Industrial chemicals", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "SORBITOL USP", company: "Shandong Food Chemical – Verified", moq: "500kg", price: "Request DDP Quote – Valid 3 Days – Only DDP", image: "https://via.placeholder.com/400x300/0e7490/ffffff?text=Sorbitol", sourceCompany: "Shandong Food Chemical", sourcePlatform: "1688", sourceUrl: "https://m.1688.com/product/sorbitol", description: "Sorbitol", grade: "Pharma Grade", tab: "Industrial chemicals" }
]
const HONEST = [
  { id: "HONEST-hpmc", name: "Hydroxypropyl Methyl Cellulose (HPMC)", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "HPMC", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/1e40af/ffffff?text=HPMC+Powder", sourceCompany: "Shanghai Honest Chem – HONEST – Comalong Building Shanghai – lannie@honestsh.com", sourcePlatform: "HONEST Catalogue Page 3", sourceUrl: "pdf#page=3", description: "White to yellowish powder – Thickener dispersant emulsifier film-forming – Tablet film coating – Methoxy 27-30% Viscosity 5-200000", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9004-65-3", originalPage: 3, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-hec", name: "Hydroxyethyl Cellulose (HEC)", subCategory: "Paint Chemicals - Natrosol, Calcium Carbonate", model: "HEC", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/2563eb/ffffff?text=HEC+Powder", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 4", sourceUrl: "pdf#page=4", description: "White yellowish powder – Water-soluble non-ionic – Thickener fluid modifier protective colloid – Viscosity H4000 3400-5000 cps", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9004-62-0", originalPage: 4, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-mcc", name: "Microcrystalline Cellulose (MCC) PH-101 PH-102", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "MCC PH101 PH102", company: "Shanghai Honest Chem – Verified – HONEST", moq: "20kg", image: "https://via.placeholder.com/400x300/0f766e/ffffff?text=MCC+PH101+PH102", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 5", sourceUrl: "pdf#page=5", description: "White powder wood pulp disintegrates rapidly – Bonding diluent disintegrating – Particle size bulk density pH ether soluble heavy metals microbial", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9004-34-6", originalPage: 5, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-cmc-pharma", name: "Carboxymethyl Cellulose Sodium (CMC) Pharma Grade", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "CMC PHARMA", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/1e3a8a/ffffff?text=CMC+Pharma+Grade", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 6", sourceUrl: "pdf#page=6", description: "White powder extreme chemical stability – Improve cracking collapsing flakes – DS 0.60 0.90 Viscosity 300-1200 pH 6.5-8.0 Moisture 8%", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9004-32-4", originalPage: 6, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-hpc", name: "Hydroxypropyl Cellulose (HPC) High Substitution H-HPC", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "HPC H-HPC", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/312e81/ffffff?text=HPC", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 7", sourceUrl: "pdf#page=7", description: "White light white powder odorless – Pellet 20 screen 99% – Thermoplastic film forming rigid polish elasticity – Low ash adhesive", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9004-64-2", originalPage: 7, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-ec", name: "Ethyl Cellulose (EC) K N T Type", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "EC K N T", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/4338ca/ffffff?text=EC", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 8", sourceUrl: "pdf#page=8", description: "White yellowing powder – Tablet adhesive film coating retarding agent slow-release – Ethoxy 45-47.9% K 48-49.5% N", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9004-57-3", originalPage: 8, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-veg-capsule", name: "Vegetable Capsule – HPMC Two-Piece Capsule", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "VEG CAPSULE HPMC", company: "Shanghai Honest Chem – Verified – HONEST", moq: "100,000 capsules", image: "https://via.placeholder.com/400x300/059669/ffffff?text=Vegetable+HPMC+Capsule", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 9", sourceUrl: "pdf#page=9", description: "Two-piece capsules cellulosic vegetarian cultural need – All natural easy swallow taste masking starch-free gluten-free – Hypromellose HPMC resistant cross-linking pH independent moisture-sensitive", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", originalPage: 9, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-film-coating", name: "Film Coating Powder – HONESTA Stomach / Intestine – Water & Alcohol Solvent", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "FILM COATING HONESTA", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/be185d/ffffff?text=Film+Coating+Powder", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 10", sourceUrl: "pdf#page=10", description: "Powder different colors drug release intestine stomach – High security reduce cost rapid configuration anti-moisture – Bead coating super light effect swallowing – Types STOMACH WATER ALCOHOL INTESTINE WATER ALCOHOL", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", originalPage: 10, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-cms-na", name: "Carboxymethyl Cellulose Sodium (CMS-NA) – Sodium Carboxymethyl Starch", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "CMS-NA", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/7c3aed/ffffff?text=CMS-NA", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 11", sourceUrl: "pdf#page=11", description: "White Powder tablet adhesives moist inflation liquidity better ideal disintegrating agent – Public adhesive thickener pharma food toothpaste oil", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9063-38-1", originalPage: 11, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-magnesium-stearate", name: "Magnesium Stearate (MS) – Lubricant", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "MS MAGNESIUM STEARATE", company: "Shanghai Honest Chem – Verified – HONEST", moq: "10kg", image: "https://via.placeholder.com/400x300/374151/ffffff?text=Magnesium+Stearate+MS", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 11", sourceUrl: "pdf#page=11", description: "White fine powder special smelly satiny feeling – Lubrication resistance glue help flow – Tablet capsule lubricant 0.25%-2.0%", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "557-04-0", originalPage: 11, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-povidone", name: "Povidone (K30/K90) – PVP", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "POVIDONE K30 K90", company: "Shanghai Honest Chem – Verified – HONEST", moq: "25kg", image: "https://via.placeholder.com/400x300/1f2937/ffffff?text=Povidone+K30+K90", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 12", sourceUrl: "pdf#page=12", description: "White milk white powder no smell hygroscopic – Wet granule adhesives low viscosity soluble water alcohols – Molecular weight big bonding better", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9003-39-8", originalPage: 12, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-crospovidone", name: "Crospovidone (PVPP) – Crosslinked Povidone", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "CROSPOVIDONE PVPP", company: "Shanghai Honest Chem – Verified – HONEST", moq: "20kg", image: "https://via.placeholder.com/400x300/4b5563/ffffff?text=Crospovidone+PVPP", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 12", sourceUrl: "pdf#page=12", description: "White almost odorless absorbency – Tablet granules pill disintegrating filling – High molecular weight crosslinking insoluble water bringing water quickly network expansion crumbling", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9003-39-8 crosslinked", originalPage: 12, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-hp-beta-cd", name: "Hydroxypropyl Beta Cyclodextrin (HP-β-CD)", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "HP-BETA-CD", company: "Shanghai Honest Chem – Verified – HONEST", moq: "5kg", image: "https://via.placeholder.com/400x300/065f46/ffffff?text=HP+Beta+Cyclodextrin", sourceCompany: "Shanghai Honest Chem – HONEST – 5kg/ctn 10kg/20kg/drum", sourcePlatform: "HONEST Catalogue Page 13 – CAS 128446-35-5 – USP35 EP7 CP2010", sourceUrl: "pdf#page=13", description: "White crystalline powder non-toxic odorless sweet – CAS 128446-35-5 – Quality USP35 EP7 CP2010 – Formula (C6H10O5)7.(C3H6O)n MW 1200-1500 – Ideal injection solubilizer drug excipients improve solubility stability bioavailability", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "128446-35-5", originalPage: 13, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-beta-cd", name: "Beta Cyclodextrin", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "BETA-CD", company: "Shanghai Honest Chem – Verified – HONEST", moq: "20kg", image: "https://via.placeholder.com/400x300/047857/ffffff?text=Beta+Cyclodextrin", sourceCompany: "Shanghai Honest Chem – HONEST – 20kg/ctn 25kg/drum", sourcePlatform: "HONEST Catalogue Page 14 – CAS 7585-39-9 – C42H70O35 MW 1134.99", sourceUrl: "pdf#page=14", description: "White crystalline powder non-toxic odorless – Circular dextrin – CAS 7585-39-9 – Formula C42H70O35 MW 1134.99 – Increase solubility dissolution prostaglandins-CD inclusion – Improve stability bioavailability reduce smell bitter stimulation slow release – Chiral separation chromatography", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "7585-39-9", originalPage: 14, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-maize-starch", name: "Maize Starch (Corn Starch)", subCategory: "Pharmaceuticals - Paracetamol, Sorbitol", model: "MAIZE STARCH CORN", company: "Shanghai Honest Chem – Verified – HONEST", moq: "20FCL", image: "https://via.placeholder.com/400x300/f59e0b/ffffff?text=Maize+Corn+Starch", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 15", sourceUrl: "pdf#page=15", description: "Much saccharide particles White Powder – Most commonly used tablet trims solid preparation filling agent – Can be pressed moisture absorption water expansion should not be used alone – With powdered sugar increase stiffness – 25KG/Bag", grade: "Food Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "9005-25-8", originalPage: 15, price: "Request DDP Quote – Valid 3 Days – Only DDP" },
  { id: "HONEST-silicon-dioxide", name: "Silicon Dioxide (SiO2) – Colloidal Silicon Dioxide – Silica", subCategory: "Commodity Chemicals - Caustic Soda, HCl, Nitric, Stearic, Acetic, H2O2", model: "SIO2 COLLOIDAL SILICA", company: "Shanghai Honest Chem – Verified – HONEST", moq: "5000KG", image: "https://via.placeholder.com/400x300/6b7280/ffffff?text=Silicon+Dioxide+SiO2", sourceCompany: "Shanghai Honest Chem – HONEST", sourcePlatform: "HONEST Catalogue Page 15 – FDA GRAS", sourceUrl: "pdf#page=15", description: "Known nature sand quartz earth crust silicates water animals plants natural human diet GRAS FDA biologically inert – Pharma anti-caking adsorbent disintegrant glidant allow powder flow freely – Protect moisture damp – 10KG/Bag MOQ 5000KG", grade: "Pharma Grade", tab: "Industrial chemicals", category: "Industrial chemicals", cas: "7631-86-9", originalPage: 15, price: "Request DDP Quote – Valid 3 Days – Only DDP" }
]
export async function GET() {
  const g = global as any
  const dyn = g.nichamProducts || []
  const all = [...BASE, ...HONEST, ...dyn]
  const map = new Map()
  for (const p of all) if (!map.has(p.id)) map.set(p.id, p)
  const unique = Array.from(map.values())
  const industrial = unique.filter((p: any) => p.category === 'Industrial chemicals' || p.tab === 'Industrial chemicals')
  return NextResponse.json({ total: unique.length, industrialTotal: industrial.length, products: unique, industrial, tab: "Industrial chemicals", message: "Industrial chemicals tab – 2 base + 16 HONEST – Catalogue extraction mechanism – Picture + data sheet – Source URL saved internally – Quote delivered to company from whose page item and picture pulled – Valid 3 Days Only DDP – Routes to AfricanIES Proc360 Laybel AI cheapest first platform fee after" })
}
